// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qawwfkjsxcneenctndtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhd3dma2pzeGNuZWVuY3RuZHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzAzMzIsImV4cCI6MjA2MjEwNjMzMn0.QOFfmkaZVtWBDlVbhPbYKb4Dio94XAyOd-D8JpS2KXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);